### ISSUE TITLE
Block trade villager

### ISSUE THREAD

**Issue by Bricec6** [Xyaafol/VilllagerModifications#1]
Hello, I like your plugin because I've been looking for a plugin in this genre for a long time and it's ultra ultra top that you released a plugin of this type.

I'd like to post a suggestion:
- Possibility to remove the exchange of an enchanted book.

for example in the configuration we could have: 

mending:
  blocktrade: true <-- then block the mending exchange
  restricted: 0
  change: 1
  material: EMERALD
  cost: 16
  book: 0
  uses: 1

for example which will be displayed like this: 
![image](https://user-images.githubusercontent.com/51750055/81009761-84d2e700-8e55-11ea-9ffb-07d7f1633e49.png)

(i'm french , sorry my english are so bad)
thanks to you and your work!

**Comment by Xyaafol** [comment]
Already possible by setting the value of 'uses' to 0 for that enchanted book.

Thank you for using my plugin.
