### ISSUE TITLE
Suggestion: Add a config option to disable XP gain from villager trades

### ISSUE THREAD

**Issue by Kwikxilver** [Xyaafol/VilllagerModifications#2]
Love the plugin and using it currently on my server.

Quick suggestion - it would be great to be able to flip a config option and disable XP from villager trades (to the player). This way, Villagers are no longer an easy source of XP to trade with.

Whether you implement it or not is up to you! Thank you for your work on this!

**Comment by Xyaafol** [comment]
Added - check the newest version on spigot.

Thanks for the suggestion!
