### ISSUE TITLE
PlayerInteractEntityEvent to VillagerModifications v1.4.3 java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by SmallSansSerif** [Xyaafol/VilllagerModifications#5]
Getting this error occasionally in my log. https://pastebin.com/4E9Vm6nw

[10:50:01 ERROR]: Could not pass event PlayerInteractEntityEvent to VillagerModifications v1.4.3
java.lang.NullPointerException: null

**Comment by Xyaafol** [comment]
This is caused by an invalid material in your config, check that all the material names are spelt correctly
